# Generated by Django 2.1.1 on 2018-10-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('idno', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
